### ISSUE TITLE
请求过滤那个地方可能有问题

### ISSUE THREAD

**Issue by blackAzrael** [xiaochonzi/mavic#1]
async def enqueue_request(self, request):
        if not request.dont_filter and not await self.df.request_seen(request):
            await self.queue.put(request)
        else:
            await self.queue.put(request)

这里是不是少了个判断

**Comment by xiaochonzi** [comment]
什么判断？

**Comment by blackAzrael** [comment]
在mavic-->core-->scheduler.py-->enqueue_request  要是设置 dont_filter=True 这样不就会永远加入不了队列了么

**Comment by xiaochonzi** [comment]
我懂你的意思了，改成以下就行了。
```
async def enqueue_request(self, request):
    if not request.dont_filter and not await self.df.request_seen(request):
       return False
    await self.queue.put(request)
    return True
```
